# Generated by Django 3.2.3 on 2021-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pw',
            field=models.CharField(max_length=20),
        ),
    ]
